---
- name: Authenticate towards Wiz GraphQL
  ansible.builtin.uri:
    url: "{{ wiz_api_auth_url }}"
    method: POST
    headers:
      Content-Type: application/x-www-form-urlencoded
    body:
      grant_type: "client_credentials"
      client_id: "{{ wiz_api_client_id }}"
      client_secret: "{{ wiz_api_client_secret }}"
      audience: "{{ wiz_api_audience }}"
    body_format: form-urlencoded
    return_content: yes
  register: token_response
  no_log: true

- name: Save Wiz token
  ansible.builtin.set_fact:
    wiz_api_bearer_token: "{{ token_response.json.access_token }}"
  no_log: true

- name: Create a service account using GraphQL
  ansible.builtin.uri:
    url: "{{ wiz_api_endpoint_url }}"
    method: POST
    headers:
      Content-Type: application/json
      Authorization: "Bearer {{ wiz_api_bearer_token }}"
    body:
      query: "{{ lookup('file', 'files/create_service_account.graphql') }}"
      variables: "{{ lookup('template', 'templates/create_service_account_variables.j2') }}"
    body_format: json
    return_content: yes
  register: created_service_account
  no_log: true

- name: Extract clientId and clientSecret
  ansible.builtin.set_fact:
    sensor_api_client_id: "{{ created_service_account.json.data.createServiceAccount.serviceAccount.clientId }}"
    sensor_api_client_secret: "{{ created_service_account.json.data.createServiceAccount.serviceAccount.clientSecret }}"
  no_log: true
