---
- name: Download Wiz Sensor RPM package to /tmp if RHS is enabled
  ansible.builtin.command:
    cmd: dnf download --downloaddir=/tmp --arch=x86_64 wiz-sensor
  when: rhs_enabled
  register: package_download
  no_log: true

- name: Find the correct RPM file for the system architecture
  ansible.builtin.find:
    paths: /tmp
    patterns: "*wiz-sensor-*.rpm"
  when: rhs_enabled
  register: rpm_file
  no_log: true

- name: Ensure environment variables are present in /etc/environment
  ansible.builtin.lineinfile:
    path: /etc/environment
    line: "{{ item }}"
    state: present
    create: yes
  loop:
    - 'WIZ_API_CLIENT_ID="{{ sensor_api_client_id }}"'
    - 'WIZ_API_CLIENT_SECRET="{{ sensor_api_client_secret }}"'
    - 'WIZ_HTTP_PROXY_URL="{{ sensor_proxy_url }}"'
    - 'LOCAL_PACKAGE="{{ rpm_file.files[0].path if rhs_enabled else "" }}"'
  when: item.split('=')[1] != '""'
  no_log: true

- name: Download Wiz Sensor install script
  ansible.builtin.command:
    cmd: curl -L https://downloads.wiz.io/sensor/sensor_install.sh -o /tmp/sensor_install.sh
  no_log: true

- name: Run Wiz Sensor install script
  ansible.builtin.command:
    cmd: sudo -E bash /tmp/sensor_install.sh
  no_log: true

- name: Remove Wiz Sensor environment variables after installation
  ansible.builtin.lineinfile:
    path: /etc/environment
    regexp: '^(WIZ_API_CLIENT_ID|WIZ_API_CLIENT_SECRET|WIZ_HTTP_PROXY_URL|LOCAL_PACKAGE)='
    state: absent
  no_log: true

- name: Remove all temporary files related to Wiz Sensor
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - /tmp/sensor_install.sh
    - "{{ rpm_file.files[0].path if rhs_enabled else '' }}"
  when: item != ""
  no_log: true
