- name: Check if Wiz Sensor SELinux module is installed
  ansible.builtin.shell: semodule -l | grep -q '^wiz-sensor$'
  register: selinux_module_check
  failed_when: false
  changed_when: false
  no_log: true

- name: Install SELinux tools
  ansible.builtin.dnf:
    name:
      - policycoreutils
      - policycoreutils-python-utils
      - selinux-policy-devel
    state: present
  when: selinux_module_check.rc != 0
  no_log: true

- name: Copy SELinux policy file
  ansible.builtin.copy:
    src: wiz-sensor.te
    dest: /tmp/wiz-sensor.te
    mode: "0640"
  when: selinux_module_check.rc != 0
  no_log: true

- name: Compile SELinux module from .te if not installed
  ansible.builtin.command:
    cmd: checkmodule -M -m -o /tmp/wiz-sensor.mod /tmp/wiz-sensor.te
  when: selinux_module_check.rc != 0
  no_log: true

- name: Build semodule package if not installed
  ansible.builtin.command:
    cmd: semodule_package -o /tmp/wiz-sensor.pp -m /tmp/wiz-sensor.mod
  when: selinux_module_check.rc != 0
  no_log: true

- name: Install SELinux module if not installed
  ansible.builtin.command:
    cmd: semodule -i /tmp/wiz-sensor.pp
  when: selinux_module_check.rc != 0
  no_log: true
