---
- name: Check if wiz-sensor package is available
  ansible.builtin.dnf:
    name: wiz-sensor
    state: present
  check_mode: yes
  register: wiz_sensor_package
  ignore_errors: yes
  changed_when: false
  no_log: true

- name: Set environment variable if wiz-sensor package is available
  ansible.builtin.set_fact:
    skip_repo: "1"
  when: wiz_sensor_package.rc == 0

- name: Ensure environment variables are present in /etc/environment
  ansible.builtin.lineinfile:
    path: /etc/environment
    line: "{{ item }}"
    state: present
    create: yes
  loop:
    - 'WIZ_API_CLIENT_ID="{{ sensor_api_client_id }}"'
    - 'WIZ_API_CLIENT_SECRET="{{ sensor_api_client_secret }}"'
    - 'WIZ_HTTP_PROXY_URL="{{ sensor_proxy_url }}"'
    - 'SKIP_ADD_REPOSITORY={{ skip_repo }}'
  when: item.split('=')[1] != '""'
  no_log: true

- name: Download Wiz Sensor install script
  ansible.builtin.command:
    cmd: "curl -L {{ sensor_install_script_url }} -o /tmp/sensor_install.sh"
  no_log: true

- name: Run Wiz Sensor install script
  ansible.builtin.command:
    cmd: sudo -E bash /tmp/sensor_install.sh
  no_log: true

- name: Remove Wiz Sensor environment variables after installation
  ansible.builtin.lineinfile:
    path: /etc/environment
    regexp: '^(WIZ_API_CLIENT_ID|WIZ_API_CLIENT_SECRET|WIZ_HTTP_PROXY_URL|SKIP_ADD_REPOSITORY)='
    state: absent
  no_log: true

- name: Remove all temporary files related to Wiz Sensor
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - /tmp/sensor_install.sh
  when: item != ""
  no_log: true
