---
- name: Ensure environment variables are present in /etc/environment
  ansible.builtin.lineinfile:
    path: /etc/environment
    line: "{{ item }}"
    state: present
    create: yes
  loop:
    - 'WIZ_API_CLIENT_ID="{{ sensor_api_client_id }}"'
    - 'WIZ_API_CLIENT_SECRET="{{ sensor_api_client_secret }}"'
    - 'WIZ_HTTP_PROXY_URL="{{ sensor_proxy_url }}"'
  when: item.split('=')[1] != '""'
  no_log: true

- name: Download Wiz Sensor install script
  ansible.builtin.get_url:
    url: https://downloads.wiz.io/sensor/sensor_install.sh
    dest: /tmp/sensor_install.sh
    mode: '0755'  # Ensure the script is executable
    checksum: sha256:your_checksum_here  # Optional: Add the actual checksum value for validation
  no_log: true

- name: Run Wiz Sensor install script
  ansible.builtin.command:
    cmd: sudo -E bash /tmp/sensor_install.sh
  no_log: true

- name: Remove Wiz Sensor environment variables after installation
  ansible.builtin.lineinfile:
    path: /etc/environment
    regexp: '^(WIZ_API_CLIENT_ID|WIZ_API_CLIENT_SECRET|WIZ_HTTP_PROXY_URL)='
    state: absent
  no_log: true
