---
- name: Pre-flight checks
  ansible.builtin.include_tasks: pre-flight.yml

- name: Install SELinux policy if SELinux is enforcing (only on RHEL)
  ansible.builtin.include_tasks: install-selinux-policy.yml
  when: rhel and ansible_facts['selinux'].get('mode', 'disabled') == 'enforcing'

- name: Create Service Account for Sensor
  ansible.builtin.include_tasks: create-service-account.yml

- name: Install Wiz Sensor on Debian systems
  ansible.builtin.include_tasks: install-sensor-debian.yml
  when: debian

- name: Install Wiz Sensor on RHEL systems
  ansible.builtin.include_tasks: install-sensor-rhel.yml
  when: rhel
